name: build
on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron: '12 0 * * *'
  workflow_dispatch:

jobs:
  build_and_test:
    name: rmf_internal_msgs
    uses: open-rmf/rmf_ci_templates/.github/workflows/reusable_build.yaml@main
    with:
      # NOTE: Avoid adding comments in the packages lines, this can break some of the called scripts in github actions
      packages: |
        rmf_charger_msgs
        rmf_dispenser_msgs
        rmf_door_msgs
        rmf_fleet_msgs
        rmf_ingestor_msgs
        rmf_lift_msgs
        rmf_obstacle_msgs
        rmf_scheduler_msgs
        rmf_site_map_msgs
        rmf_task_msgs
        rmf_traffic_msgs
        rmf_workcell_msgs
        rmf_task_ros2
        rmf_traffic_ros2
        rmf_fleet_adapter